// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChainedSelectTeacherController from "./chained_select_teacher_controller"
application.register("chained-select-teacher", ChainedSelectTeacherController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
